#--------------------------------------------

name: My-GitHubActions-Actions
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha}}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello, World, form Testing job!!!"
    - name: Execute few commands
      run: |
        echo "1"
        echo "2"
        echo "App name: ${{ env.APPLICATION_NAME}}"
    - name: List folder
      run : ls -la 

  my_deploy:
     needs: [my_testing]
     runs-on: ubuntu-latest
     
     steps:
     - name: Print Hello Message in Deploy
       run: echo "Hello, World, form Deploy job!!!"
       
     - name: Print Deployment package
       run : echo "Deploy package naem is ${{ env.DEPLOY_PACKAGE_NAME}}"
    
