#--------------------------------------------

name: My-GitHubActions-Actions

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello, World, form Testing job!!!"

  my_deploy:
     runs-on: ubuntu-latest
     
     steps:
     - name: Print Hello Message
       run: echo "Hello, World, form Deploy job!!!"
    
