on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Echo var
        run: |
               echo "$(echo $GITHUB_REF | cut -d'/' -f 3)"
               echo "$(git diff --name-only origin/testing origin/master)"
               echo "!"
