on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: 'master'
          ref: 'testing'

      - name: Echo var
        run: |
               echo "$(echo $GITHUB_REF | cut -d'/' -f 3)"
               echo "$(git branch)"
               echo "$(git diff testing master)"

